Auth redirect
samthatcode/CrownBirthEvent pull request #3
Opened 2024-08-17 16:56 UTC by techtheo

new

2024-08-18 19:46 UTC, samthatcode commented on src/plugins/vuetify.js
There was no need to Import Vuetify components as they are already available when you install the library. All u needed to do was import the component and directives like this:

// Vuetify
import 'vuetify/styles'
import { createVuetify } from 'vuetify';
import * as components from 'vuetify/components';
import * as directives from 'vuetify/directives';

and register it like this:

const vuetify = createVuetify({
    components,
    directives,
});


app.use(vuetify);

2024-08-18 20:56 UTC, samthatcode requested changes
Overall, Your code is buggy and needs to be fixed, Please follow convention and best practice. Remove codes that you don't use to ensure clean code and style. Comment out your console.log statement after you have tested things out.

2024-08-18 20:56 UTC, samthatcode commented on src/router/index.js
You should lazy load components that are routed like this:  {
      path: '/about',
      name: 'about',
      component: () => import('../views/AboutView.vue')
    }
    
    It enhances the performance of the web page and the components are only loaded when they are routed to, It's code splitting and it means that they won't load when the app first mounts until they are visited.

2024-08-18 20:56 UTC, samthatcode commented on src/plugins/vuetify.js
There was no need to Import Vuetify components as they are already available when you install the library. All u needed to do was import the component and directives like this:

// Vuetify
import 'vuetify/styles'
import { createVuetify } from 'vuetify';
import * as components from 'vuetify/components';
import * as directives from 'vuetify/directives';

and register it like this:

const vuetify = createVuetify({
    components,
    directives,
});


app.use(vuetify);

2024-08-18 20:56 UTC, samthatcode commented on src/components/UserProfile.vue
I was able to update my username and email without signing up with those credentials. Fix that bug: You have to do a check. also i should not even be able to update that credentials if im not a user or if i have not signed up for an account

2024-08-18 20:56 UTC, samthatcode commented on src/views/BookEvent.vue
I was able to click on the Proceed to payment button and it was successful without booking an event. Also, the Venue filed that is supposed to be a drop down, venues available didn't get populated. Fix that.

2024-08-28 09:20 UTC, techtheo commented
Added  booking features

2024-08-28 09:37 UTC, techtheo reviewed
added new features

2024-08-28 16:03 UTC, techtheo commented
fixed paystack payment gateway

2024-08-30 13:18 UTC, techtheo commented
The Proceed to Payment button now working perfectly well on the ViewBookEvent page

2024-08-30 16:10 UTC, techtheo commented
Fully completed features for user and admin

2024-09-03 05:13 UTC, merged